[package]

name = "cesu8"
version = "0.0.1"
authors = ["Eric Kidd <git@randomhacks.net>"]

description = "Convert to and from CESU-8 encoding (similar to UTF-8)"
license = "Apache-2.0/MIT"

repository = "https://github.com/emk/cesu8-rs"
